routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use \App\User;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/dev-login/{token}','Auth\LoginController@devlogin')->name('dev-login');
Route::get('/', 'AdminController@index')->name('admin');
Route::get('/admin', 'AdminController@index')->name('admin');
Route::resource('admin/usuarios', 'UsersController');
Route::post('admin/catalogo/comentarioUsuario', 'CatalogoController@guardaComentarioUsuario');
Route::post('admin/catalogo/email', 'CatalogoController@sendEmailPaciente');
Route::resource('admin/catalogo', 'CatalogoController');
Route::resource('admin/categorias/combos', 'CategoriasCombosController');
Route::get('admin/categorias/alimentos/{id}', 'CategoriesController@alimentos');
Route::resource('admin/categorias', 'CategoriesController');
Route::resource('admin/tiempos', 'TiemposController');
Route::resource('admin/ingredientes', 'IngredientesController');
Route::resource('admin/supermercados', 'SupermercadosController');
Route::resource('admin/alimentos/galerias', 'AlimentosGaleriasController');
Route::get('admin/alimentos/verificar', 'AlimentosController@verificar');
Route::get('/admin/alimentos/usuario', 'AlimentosController@misalimentos');
Route::get('/admin/alimentos/favoritos', 'AlimentosController@favoritos');
Route::resource('admin/alimentos', 'AlimentosController');
Route::put('admin/alimentos/loadSecondImage/{id}', 'AlimentosController@loadSecondImage');
Route::put('admin/alimentos/informacionGeneral/{id}', 'AlimentosController@addInformacionGeneral');
Route::put('admin/alimentos/macronutrientes/{id}', 'AlimentosController@addMacronutrientes');
Route::put('admin/alimentos/informacionConsumo/{id}', 'AlimentosController@addInformacionConsumo');
Route::put('admin/alimentos/materialAdicional/{id}', 'AlimentosController@addMaterialAdicional');
Route::put('admin/alimentos/keywords/{id}', 'AlimentosController@addKeywords');
Route::post('admin/alimentos/galeria', 'AlimentosController@addGaleria');
Route::put('admin/alimentos/validar/{id}', 'AlimentosController@validarCampos');
Route::put('admin/alimentos/sendToValidate/{id}', 'AlimentosController@ChangeStatusValidar');
Route::any('admin/search', 'AlimentosController@buscador');
Route::post('/login', 'Auth\LoginController@authenticate');
Route::get('/logout', 'Auth\LoginController@logout');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Food;

class User extends Authenticatable
{

    use Notifiable;

    //protected $table = 'usuarios';
    protected $table = 'usuarios';
    protected $connection = 'mysql2';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'usuario', 'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /*public function setPasswordAttribute($password){

        $this->attributes['password_encriptada'] = bcrypt($password);
        $this->attributes['password'] = $password;
        $this->attributes['password_crypt'] = $password;

    }
    public function getAuthPassword()
    {
        return $this->password_encriptada;
    }*/
    public function getAuthPassword()
    {
        return $this->password;
    }
    public function hasRole($role, $id)
    {
        return User::where('tipo_usuario', '=', $role)->where('id', '=', $id)->get()->count();
    }
    public function foods()
    {
        return $this->hasMany(Food::class, 'id_nut');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App;
use \App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $users = User::all();
        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {



        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\CreateUserRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $verifier = App::make('validation.presence');

        $verifier->setConnection('mysql2');

        $validator = Validator::make($request->all(), [
            'nombre'         => 'required',
            'usuario'        => 'required|unique:usuarios,usuario',
            'password'       => 'required|confirmed'
        ]);

        $validator->setPresenceVerifier($verifier);

        date_default_timezone_set('America/Mexico_City');
        $fecha_alta = date("Y-m-d H:i:s");
        $request->merge(['fecha_alta' => $fecha_alta]);
        $user = User::create($request->all());
        $user->save();
        return redirect()->route('usuarios.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $usuario = User::findOrFail($id);

        //$this->authorize('edit',$usuario);


        return view('users.edit', compact('usuario'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $verifier = App::make('validation.presence');

        $verifier->setConnection('mysql2');

        $validator = Validator::make($request->all(), [
            'nombre'        => 'required',
            'usuario'       => 'required|unique:usuarios,usuario,' . $this->route('usuario'),
        ]);

        $validator->setPresenceVerifier($verifier);


        $usuario = User::findOrFail($id);

        //$this->authorize('update',$usuario);

        $usuario->update($request->all());

        return back()->with('info', 'Usuario actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $usuario = User::findOrFail($id);

        $this->authorize('destroy', $usuario);

        $usuario->delete();

        return back();
    }
    public function AuthRouteAPI(Request $request)
    {
        return $request->user();
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('title','Alta Usuarios')

@section('content')

<div class="container">
		<h1>Crear Usuario</h1>
		@if (session()->has('info'))
			 <div class="alert alert-success">
			 	 {{ session('info') }}	
			 </div>
		@endif
		<form method="POST" action="{{ route('usuarios.store') }}">
			@include('users.form',['usuario' => new App\User ])
			<button type="submit" class="btn btn-info btn-xs">Guardar</button>
		</form>
	</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('title','Editar Usuarios')

@section('content')
	<div class="container">
		<h1>Editar Usuario</h1>
		@if (session()->has('info'))
			 <div class="alert alert-success">
			 	 {{ session('info') }}	
			 </div>
			
		@endif
		<form method="POST" action="{{ route('usuarios.update', $usuario->id) }}">
			{!! method_field('PUT') !!}
			
			@include('users.form')
			<button type="submit" class="btn btn-info btn-xs">Guardar</button>
		</form>
	</div>
@endsection

resources/views/users/form.blade.php
{!! csrf_field() !!}
<div class="form-row">
    <div class="form-group col-md-4">
		<label class=" custom-label-class" for="nombre">
			Nombre
			<input type="text" name="nombre" class="form-control" value="{{ old('nombre',$usuario->nombre ?? '') }}">
				{!! $errors->first('nombre','<span class=error>:message</span>') !!}
		</label>
    </div>
	<div class="form-group col-md-4">
		<label class=" custom-label-class" for="a_paterno">
			Apellido Paterno 
			<input type="text" name="a_paterno" class="form-control" value="{{ old('a_paterno',$usuario->a_paterno ?? '') }}">
			{!! $errors->first('a_paterno','<span class=error>:message</span>') !!}
		</label>
    </div>
	<div class="form-group col-md-4">
		<label for="name">
			Apellido Materno 
			<input type="text" name="a_materno" class="form-control" value="{{ old('a_materno',$usuario->a_materno ?? '') }}">
			{!! $errors->first('a_materno','<span class=error>:message</span>') !!}
		</label>
    </div>
	<div class="form-group col-md-4">
			<label for="usuario">
				Usuario 
				<input type="text" name="usuario" class="form-control" value="{{  old('usuario',$usuario->usuario ?? '') }}">
				{!! $errors->first('usuario','<span class=error>:message</span>') !!}
			</label>
    </div>
	
	@unless($usuario->id)
	<div class="form-group col-md-4">
		<label for="password">
			Password  
			<input type="password" name="password" class="form-control">
			{!! $errors->first('password','<span class=error>:message</span>') !!}
		</label>
	</div>
	<div class="form-group col-md-4">
		<label for="password_confirmation">
			Password Confirm 
			<input type="password" name="password_confirmation" class="form-control">
			{!! $errors->first('password_confirmation','<span class=error>:message</span>') !!}
		</label>
	</div>
	@endunless
	<div class="form-group col-md-4">
			<label for="tipo_usuario">
				Tipo 
				<input type="text" name="tipo_usuario" class="form-control" value="{{  old('tipo_usuario',$usuario->tipo_usuario ?? '') }}">
				{!! $errors->first('tipo_usuario','<span class=error>:message</span>') !!}
			</label>
    </div>
	<div class="form-group col-md-4">
			<label for="puesto">
				Puesto 
				<input type="text" name="puesto" class="form-control" value="{{  old('puesto',$usuario->puesto ?? '') }}">
				{!! $errors->first('puesto','<span class=error>:message</span>') !!}
			</label>
    </div>
	<div class="form-group col-md-4">
			<label for="status">
				Status 
				<input type="text" name="status" class="form-control" value="{{  old('status',$usuario->status ?? '') }}">
				{!! $errors->first('status','<span class=error>:message</span>') !!}
			</label>
    </div>
	<div class="form-group col-md-4">
			<label for="administrador">
				Administrador 
				<input type="text" name="administrador" class="form-control" value="{{  old('administrador',$usuario->administrador ?? '') }}">
				{!! $errors->first('administrador','<span class=error>:message</span>') !!}
			</label>
    </div>
	<div class="form-group col-md-4">
		<label for="whatsapp">
		whatsapp 
				<input type="text" name="whatsapp" class="form-control" value="{{  old('whatsapp',$usuario->whatsapp ?? '') }}">
				{!! $errors->first('whatsapp','<span class=error>:message</span>') !!}
		</label>
	</div>
	<div class="form-group col-md-4">
		<label for="whatsapp_empresa">
		whatsapp empresa
				<input type="text" name="whatsapp_empresa" class="form-control" value="{{  old('whatsapp_empresa',$usuario->whatsapp_empresa ?? '') }}">
				{!! $errors->first('whatsapp_empresa','<span class=error>:message</span>') !!}
		</label>
	</div>
	<div class="form-group col-md-4">
		<label for="whatsappstring">
		whatsapp String
				<input type="text" name="whatsappstring" class="form-control" value="{{  old('whatsappstring',$usuario->whatsappstring ?? '') }}">
				{!! $errors->first('whatsappstring','<span class=error>:message</span>') !!}
		</label>
	</div>
	<div class="form-group col-md-4">
		<label for="correo">
				Email 
				<input type="text" name="correo" class="form-control" value="{{  old('correo',$usuario->correo ?? '') }}">
				{!! $errors->first('correo','<span class=error>:message</span>') !!}
		</label>
	</div>
	<div class="form-group col-md-4">
		<label for="correo_password">
				Email password
				<input type="text" name="correo_password" class="form-control" value="{{  old('correo_password',$usuario->correo_password ?? '') }}">
				{!! $errors->first('correo_password','<span class=error>:message</span>') !!}
		</label>
	</div>
	<div class="form-group col-md-4">
		<label for="correo_personal">
				Email personal
				<input type="text" name="correo_personal" class="form-control" value="{{  old('correo_personal',$usuario->correo_personal ?? '') }}">
				{!! $errors->first('correo_personal','<span class=error>:message</span>') !!}
		</label>
	</div>
	<div class="form-group col-md-4">
		<label for="correo_personal_ok">
				Email personal ok
				<input type="text" name="correo_personal_ok" class="form-control" value="{{  old('correo_personal_ok',$usuario->correo_personal_ok ?? '') }}">
				{!! $errors->first('correo_personal_ok','<span class=error>:message</span>') !!}
		</label>
	</div>
	<div class="form-group col-md-4">
		<label for="sexo">
				Sexo
				<input type="text" name="sexo" class="form-control" value="{{  old('sexo',$usuario->sexo ?? '') }}">
				{!! $errors->first('sexo','<span class=error>:message</span>') !!}
		</label>
	</div>
	<div class="form-group col-md-4">
		<label for="lada">
				Lada
				<input type="text" name="lada" class="form-control" value="{{  old('lada',$usuario->lada ?? '') }}">
				{!! $errors->first('lada','<span class=error>:message</span>') !!}
		</label>
	</div>
	<div class="form-group col-md-4">
		<label for="pais">
				País
				<input type="text" name="pais" class="form-control" value="{{  old('pais',$usuario->pais ?? '') }}">
				{!! $errors->first('pais','<span class=error>:message</span>') !!}
		</label>
	</div>
	<div class="form-group col-md-4">
		<label for="sucursal">
				Sucursal
				<input type="text" name="sucursal" class="form-control" value="{{  old('sucursal',$usuario->sucursal ?? '') }}">
				{!! $errors->first('sucursal','<span class=error>:message</span>') !!}
		</label>
	</div>
	<div class="form-group col-md-4">
		<label for="banco_clabe">
		banco_clabe
				<input type="text" name="banco_clabe" class="form-control" value="{{  old('banco_clabe',$usuario->banco_clabe ?? '') }}">
				{!! $errors->first('banco_clabe','<span class=error>:message</span>') !!}
		</label>
	</div>
	<div class="form-group col-md-4">
		<label for="banco">
		banco
				<input type="text" name="banco" class="form-control" value="{{  old('banco',$usuario->banco ?? '') }}">
				{!! $errors->first('banco','<span class=error>:message</span>') !!}
		</label>
	</div>
	<div class="form-group col-md-4">
		<label for="cuenta">
		Cuenta
				<input type="text" name="cuenta" class="form-control" value="{{  old('cuenta',$usuario->cuenta ?? '') }}">
				{!! $errors->first('cuenta','<span class=error>:message</span>') !!}
		</label>
	</div>
	<div class="form-group col-md-4">
		<label for="ciudad">
		Ciudad
				<input type="text" name="ciudad" class="form-control" value="{{  old('ciudad',$usuario->ciudad ?? '') }}">
				{!! $errors->first('ciudad','<span class=error>:message</span>') !!}
		</label>
	</div>
	<div class="form-group col-md-4">
		<label for="cedula_ok">
		Cedula
				<input type="text" name="cedula_ok" class="form-control" value="{{  old('cedula_ok',$usuario->cedula_ok ?? '') }}">
				{!! $errors->first('cedula_ok','<span class=error>:message</span>') !!}
		</label>
	</div>
	<div class="form-group col-md-4">
		<label for="ine_ok">
		INE
				<input type="text" name="ine_ok" class="form-control" value="{{  old('ine_ok',$usuario->ine_ok ?? '') }}">
				{!! $errors->first('ine_ok','<span class=error>:message</span>') !!}
		</label>
	</div>
	<div class="form-group col-md-4">
		<label for="ine_back_ok">
		INE Back
				<input type="text" name="ine_back_ok" class="form-control" value="{{  old('ine_back_ok',$usuario->ine_back_ok ?? '') }}">
				{!! $errors->first('ine_back_ok','<span class=error>:message</span>') !!}
		</label>
	</div>
</div>	
<hr>

resources/views/users/index.blade.php
@extends('layouts.app')

@section('title','Usuarios')

@section('content')
	<div class="container __listados_general">
		<h3>Usuarios</h3>
		<div class="__acciones_buttons btn-group">
			<a href="{{ route('usuarios.create') }}" class="btn btn-default btn-outline-dark">Nuevo Usuario</a>
		</div>
		<table class="table">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Nombre</th>
		      <th scope="col">Usuario</th>
		      <th scope="col">Email</th>
		      <th scope="col">Role</th>
		      <th scope="col"></th>
		    </tr>
		  </thead>
		  <tbody>
		  	@foreach($users as $user)
				<tr>
			      <th scope="row">{{ $loop->iteration }}</th>
			      <td>{{ $user->nombre }} {{ $user->a_materno }} {{ $user->a_paterno }}</td>
			      <td>{{ $user->usuario }}</td>
			      <td>{{ $user->email }}</td>
			      <td>
			      	{{ $user->tipo_usuario }}
			      	
			      </td>
			      <td>
			      	<div class="btn-group __acciones_buttons_grupo">
						<a class="btn btn-default btn-outline-dark __accion_registro" href="{{ route('usuarios.edit', $user->id) }}">
								<i class="el el-pencil"></i> Editar
						</a>
						<div class="dropdown __accion_registro">
						  <button class="btn btn-default btn-outline-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Más
						  </button>
						  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
						    <form style = "display: inline;" method = 'POST'  action = "{{ route('usuarios.destroy', $user->id) }}" >
						  		{!! csrf_field() !!}
						  		{!! method_field('DELETE') !!}
						  		<button class="dropdown-item" type="submit">
						  			<i class="el el-remove text-danger"></i> <span class="text-danger">Eliminar</span>
						  		</button>
						  	</form>
						  </div>
						</div>
					</div>
			      </td>	
			    </tr>

		  	@endforeach
		    
		  </tbody>
		</table>
	</div>
@endsection